export const documentPage = {
  quotes: 'Quotes',
  actives: 'Actives',
  averageProfit: 'Average profit',
  currentAssets: 'Current assets',
  currentRevenue: 'Current revenue',
  equity: 'Equity',
  lastYearRevenue: 'Last year revenue',
  profit: 'Profit',
  quarterlyProfit: 'Quarterly profit',
  quarterlyRevenue: 'Quarterly revenue',
  returnOnEquity: 'Return on equity',
  shareOfEquityInAssets: 'Share of equity in assets',
  yearSlidingProfit: 'Year sliding profit',
  yearSlidingRevenue: 'Year sliding revenue',
};
